version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - mongodata:/data/db
    networks:
      - microportal

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - microportal

  keycloak:
    image: jboss/keycloak
    links:
      - postgres
    ports:
      - 7000:8080
    environment:
      - TZ=America/Sao_Paulo
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    networks:
      - microportal

  ## FRONTENDS

  microportal:
    image: microportal/microportal:1.0.0-SNAPSHOT
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - microportal

  core-ui:
    image: microportal/core-ui:1.0.0-SNAPSHOT
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - microportal

  login-ui:
    image: microportal/login-ui:1.0.0-SNAPSHOT
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - microportal

  ## BACKENDS

  core-service:
    image: microportal/core-service:1.0.0-SNAPSHOT
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=portaldb
      - JAVA_OPTS=-Xms32m -Xmx64m -XX:MetaspaceSize=32m -XX:MaxMetaspaceSize=96m
    networks:
      - microportal

  login-service:
    image: microportal/login-service:1.0.0-SNAPSHOT
    environment:
      - TZ=America/Sao_Paulo
      - KEYCLOAK_CLIENT_ID=microportal
      - KEYCLOAK_CLIENT_SECRET=b56f5388-f2b6-4f9c-be59-48fed7294f43
      - KEYCLOAK_REALM=MicroportalRealm
      - KEYCLOAK_URL=http://keycloak:8080/
    networks:
      - microportal

  ## Reverse proxy

  nginx:
    image: nginx:stable-alpine
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/microportal.crt:/etc/nginx/microportal.crt
      - ./nginx/microportal.key:/etc/nginx/microportal.key
    networks:
      - microportal

volumes:
  pgdata:
  mongodata:

networks:
  microportal:
